baseurl: "" # OPTIONAL: the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com
destination: output

development:
  url: "localhost:4000"

template_engine: erb
permalink: pretty

collection:
  posts:
    output: true
    permalink: pretty

pagination:
  enabled: true

defaults:
  - scope:
      path: "images"
    values:
      image: true

  - scope:
      collection: posts
    values:
      layout: post
      permalink: /posts/:year/:month/:day/:slug
