baseurl: "" # OPTIONAL: the subpath of your site, e.g. /blog
url: "https://konnorrogers.com" # the base hostname & protocol for your site, e.g. https://example.com
destination: output

development:
  url: "localhost:4000"
  unpublished: true

template_engine: erb

permalink: "/posts/:year/:slug/"

collections:
  posts:
    output: true
  projects:
    output: true
    permalink: "/projects/:slug/"

pagination:
  enabled: true

defaults:
  - scope:
      path: "images"
    values:
      image: true

  - scope:
      path: "_posts"
    values:
      layout: post

  - scope:
      path: "_projects"
    values:
      layout: project

  # - scope:
  #     path: ""
  #   values:
  #     image: /assets/images/default-card.png
