baseurl: "" # OPTIONAL: the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. https://example.com
destination: output

development:
  url: "localhost:4000"

template_engine: erb

permalink: "/posts/:year/:slug/"

collection:
  pages:
    output: true
    permalink: pretty
  posts:
    output: true

pagination:
  enabled: true

defaults:
  - scope:
      path: "images"
    values:
      image: true

  - scope:
      scope: "_posts"
    values:
      layout: post
